### ISSUE TITLE
Bug when cookie value is empty string

### ISSUE THREAD

**Issue by ct-badger** [Jayshua/simple-cookie#1]
https://github.com/Jayshua/simple-cookie/blob/f12bcacdcb0d4632c99a5a6a3eb25d38bcd7b47e/src/lib.rs#L94

If the cookie value is an empty string then this line panics.

I ended up overriding the function and adding a check for empty strings, but there is very likely a more elegant solution: 
```rust 
if (slice.len() == 0) {
        tracing::debug!("Cookie had empty value; returning empty string slice");
        return &[]
    }
```

**Comment by Jayshua** [comment]
Took me a while to get back to this, but the 2.0 version I just published doesn't use trim_ascii_whitespace at all anymore now that [u8].trim_ascii() has stabilized. This should be fixed now, thanks for filing the issue!

P.S. I've added "Never panic" to my list of goals for this library, so if you find any more panics definitely let me know.
